apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-couchdb-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-couchdb-exporter.name" . }}
    chart: {{ template "prometheus-couchdb-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/port: "9984"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "prometheus-couchdb-exporter.name" . }}
    release: {{ .Release.Name }}
