apiVersion: v1
entries:
  prometheus-couchdb-exporter:
  - apiVersion: v1
    appVersion: "22"
    created: "2020-06-16T18:25:38.7816642-05:00"
    description: A Helm chart to export the metrics from couchdb in Prometheus format.
    digest: a6b591cf60650ae4272ad755345836a096b568f162cc8e8381ef826f2b88c41a
    home: https://gkarthiks.github.io/helm-charts/charts/couchdb-prometheus-exporter
    keywords:
    - couchdb-exporter
    - prometheus
    maintainers:
    - email: github.gkarthiks@gmail.com
      name: gkarthiks
    name: prometheus-couchdb-exporter
    sources:
    - https://github.com/gesellix/couchdb-prometheus-exporter
    urls:
    - prometheus-couchdb-exporter-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-16T18:25:38.7816642-05:00"
